// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: klogist.proto

package kdevelop.klogist.proto;

public final class KlogistProtos {
  private KlogistProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:klogist.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code klogist.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:klogist.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kdevelop.klogist.proto.KlogistProtos.Person.class, kdevelop.klogist.proto.KlogistProtos.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static kdevelop.klogist.proto.KlogistProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(kdevelop.klogist.proto.KlogistProtos.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code klogist.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:klogist.Person)
        kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kdevelop.klogist.proto.KlogistProtos.Person.class, kdevelop.klogist.proto.KlogistProtos.Person.Builder.class);
      }

      // Construct using kdevelop.klogist.proto.KlogistProtos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_Person_descriptor;
      }

      public kdevelop.klogist.proto.KlogistProtos.Person getDefaultInstanceForType() {
        return kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance();
      }

      public kdevelop.klogist.proto.KlogistProtos.Person build() {
        kdevelop.klogist.proto.KlogistProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kdevelop.klogist.proto.KlogistProtos.Person buildPartial() {
        kdevelop.klogist.proto.KlogistProtos.Person result = new kdevelop.klogist.proto.KlogistProtos.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kdevelop.klogist.proto.KlogistProtos.Person) {
          return mergeFrom((kdevelop.klogist.proto.KlogistProtos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kdevelop.klogist.proto.KlogistProtos.Person other) {
        if (other == kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kdevelop.klogist.proto.KlogistProtos.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kdevelop.klogist.proto.KlogistProtos.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:klogist.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:klogist.Person)
  }

  public interface ReqAddPersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:klogist.ReqAddPerson)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .klogist.Person person = 1;</code>
     */
    boolean hasPerson();
    /**
     * <code>optional .klogist.Person person = 1;</code>
     */
    kdevelop.klogist.proto.KlogistProtos.Person getPerson();
    /**
     * <code>optional .klogist.Person person = 1;</code>
     */
    kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder getPersonOrBuilder();
  }
  /**
   * Protobuf type {@code klogist.ReqAddPerson}
   */
  public static final class ReqAddPerson extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:klogist.ReqAddPerson)
      ReqAddPersonOrBuilder {
    // Use ReqAddPerson.newBuilder() to construct.
    private ReqAddPerson(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqAddPerson(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqAddPerson defaultInstance;
    public static ReqAddPerson getDefaultInstance() {
      return defaultInstance;
    }

    public ReqAddPerson getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqAddPerson(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              kdevelop.klogist.proto.KlogistProtos.Person.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = person_.toBuilder();
              }
              person_ = input.readMessage(kdevelop.klogist.proto.KlogistProtos.Person.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(person_);
                person_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_ReqAddPerson_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_ReqAddPerson_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kdevelop.klogist.proto.KlogistProtos.ReqAddPerson.class, kdevelop.klogist.proto.KlogistProtos.ReqAddPerson.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqAddPerson> PARSER =
        new com.google.protobuf.AbstractParser<ReqAddPerson>() {
      public ReqAddPerson parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqAddPerson(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqAddPerson> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PERSON_FIELD_NUMBER = 1;
    private kdevelop.klogist.proto.KlogistProtos.Person person_;
    /**
     * <code>optional .klogist.Person person = 1;</code>
     */
    public boolean hasPerson() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .klogist.Person person = 1;</code>
     */
    public kdevelop.klogist.proto.KlogistProtos.Person getPerson() {
      return person_;
    }
    /**
     * <code>optional .klogist.Person person = 1;</code>
     */
    public kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder getPersonOrBuilder() {
      return person_;
    }

    private void initFields() {
      person_ = kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, person_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(kdevelop.klogist.proto.KlogistProtos.ReqAddPerson prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code klogist.ReqAddPerson}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:klogist.ReqAddPerson)
        kdevelop.klogist.proto.KlogistProtos.ReqAddPersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_ReqAddPerson_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_ReqAddPerson_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kdevelop.klogist.proto.KlogistProtos.ReqAddPerson.class, kdevelop.klogist.proto.KlogistProtos.ReqAddPerson.Builder.class);
      }

      // Construct using kdevelop.klogist.proto.KlogistProtos.ReqAddPerson.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance();
        } else {
          personBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_ReqAddPerson_descriptor;
      }

      public kdevelop.klogist.proto.KlogistProtos.ReqAddPerson getDefaultInstanceForType() {
        return kdevelop.klogist.proto.KlogistProtos.ReqAddPerson.getDefaultInstance();
      }

      public kdevelop.klogist.proto.KlogistProtos.ReqAddPerson build() {
        kdevelop.klogist.proto.KlogistProtos.ReqAddPerson result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kdevelop.klogist.proto.KlogistProtos.ReqAddPerson buildPartial() {
        kdevelop.klogist.proto.KlogistProtos.ReqAddPerson result = new kdevelop.klogist.proto.KlogistProtos.ReqAddPerson(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (personBuilder_ == null) {
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kdevelop.klogist.proto.KlogistProtos.ReqAddPerson) {
          return mergeFrom((kdevelop.klogist.proto.KlogistProtos.ReqAddPerson)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kdevelop.klogist.proto.KlogistProtos.ReqAddPerson other) {
        if (other == kdevelop.klogist.proto.KlogistProtos.ReqAddPerson.getDefaultInstance()) return this;
        if (other.hasPerson()) {
          mergePerson(other.getPerson());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kdevelop.klogist.proto.KlogistProtos.ReqAddPerson parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kdevelop.klogist.proto.KlogistProtos.ReqAddPerson) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private kdevelop.klogist.proto.KlogistProtos.Person person_ = kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          kdevelop.klogist.proto.KlogistProtos.Person, kdevelop.klogist.proto.KlogistProtos.Person.Builder, kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder> personBuilder_;
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      public boolean hasPerson() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      public kdevelop.klogist.proto.KlogistProtos.Person getPerson() {
        if (personBuilder_ == null) {
          return person_;
        } else {
          return personBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      public Builder setPerson(kdevelop.klogist.proto.KlogistProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          person_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      public Builder setPerson(
          kdevelop.klogist.proto.KlogistProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          person_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      public Builder mergePerson(kdevelop.klogist.proto.KlogistProtos.Person value) {
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              person_ != kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance()) {
            person_ =
              kdevelop.klogist.proto.KlogistProtos.Person.newBuilder(person_).mergeFrom(value).buildPartial();
          } else {
            person_ = value;
          }
          onChanged();
        } else {
          personBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance();
          onChanged();
        } else {
          personBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      public kdevelop.klogist.proto.KlogistProtos.Person.Builder getPersonBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      public kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder getPersonOrBuilder() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          return person_;
        }
      }
      /**
       * <code>optional .klogist.Person person = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          kdevelop.klogist.proto.KlogistProtos.Person, kdevelop.klogist.proto.KlogistProtos.Person.Builder, kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              kdevelop.klogist.proto.KlogistProtos.Person, kdevelop.klogist.proto.KlogistProtos.Person.Builder, kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder>(
                  getPerson(),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:klogist.ReqAddPerson)
    }

    static {
      defaultInstance = new ReqAddPerson(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:klogist.ReqAddPerson)
  }

  public interface RespPersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:klogist.RespPerson)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 Result = 1 [default = 0];</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 Result = 1 [default = 0];</code>
     */
    int getResult();

    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    java.util.List<kdevelop.klogist.proto.KlogistProtos.Person> 
        getPersonList();
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    kdevelop.klogist.proto.KlogistProtos.Person getPerson(int index);
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    java.util.List<? extends kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code klogist.RespPerson}
   */
  public static final class RespPerson extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:klogist.RespPerson)
      RespPersonOrBuilder {
    // Use RespPerson.newBuilder() to construct.
    private RespPerson(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RespPerson(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RespPerson defaultInstance;
    public static RespPerson getDefaultInstance() {
      return defaultInstance;
    }

    public RespPerson getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RespPerson(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                person_ = new java.util.ArrayList<kdevelop.klogist.proto.KlogistProtos.Person>();
                mutable_bitField0_ |= 0x00000002;
              }
              person_.add(input.readMessage(kdevelop.klogist.proto.KlogistProtos.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_RespPerson_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_RespPerson_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kdevelop.klogist.proto.KlogistProtos.RespPerson.class, kdevelop.klogist.proto.KlogistProtos.RespPerson.Builder.class);
    }

    public static com.google.protobuf.Parser<RespPerson> PARSER =
        new com.google.protobuf.AbstractParser<RespPerson>() {
      public RespPerson parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RespPerson(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RespPerson> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 Result = 1 [default = 0];</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Result = 1 [default = 0];</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int PERSON_FIELD_NUMBER = 2;
    private java.util.List<kdevelop.klogist.proto.KlogistProtos.Person> person_;
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    public java.util.List<kdevelop.klogist.proto.KlogistProtos.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    public java.util.List<? extends kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    public kdevelop.klogist.proto.KlogistProtos.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .klogist.Person person = 2;</code>
     */
    public kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      result_ = 0;
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(2, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static kdevelop.klogist.proto.KlogistProtos.RespPerson parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(kdevelop.klogist.proto.KlogistProtos.RespPerson prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code klogist.RespPerson}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:klogist.RespPerson)
        kdevelop.klogist.proto.KlogistProtos.RespPersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_RespPerson_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_RespPerson_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kdevelop.klogist.proto.KlogistProtos.RespPerson.class, kdevelop.klogist.proto.KlogistProtos.RespPerson.Builder.class);
      }

      // Construct using kdevelop.klogist.proto.KlogistProtos.RespPerson.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kdevelop.klogist.proto.KlogistProtos.internal_static_klogist_RespPerson_descriptor;
      }

      public kdevelop.klogist.proto.KlogistProtos.RespPerson getDefaultInstanceForType() {
        return kdevelop.klogist.proto.KlogistProtos.RespPerson.getDefaultInstance();
      }

      public kdevelop.klogist.proto.KlogistProtos.RespPerson build() {
        kdevelop.klogist.proto.KlogistProtos.RespPerson result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kdevelop.klogist.proto.KlogistProtos.RespPerson buildPartial() {
        kdevelop.klogist.proto.KlogistProtos.RespPerson result = new kdevelop.klogist.proto.KlogistProtos.RespPerson(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kdevelop.klogist.proto.KlogistProtos.RespPerson) {
          return mergeFrom((kdevelop.klogist.proto.KlogistProtos.RespPerson)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kdevelop.klogist.proto.KlogistProtos.RespPerson other) {
        if (other == kdevelop.klogist.proto.KlogistProtos.RespPerson.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000002);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kdevelop.klogist.proto.KlogistProtos.RespPerson parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kdevelop.klogist.proto.KlogistProtos.RespPerson) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>required int32 Result = 1 [default = 0];</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Result = 1 [default = 0];</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 Result = 1 [default = 0];</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Result = 1 [default = 0];</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<kdevelop.klogist.proto.KlogistProtos.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          person_ = new java.util.ArrayList<kdevelop.klogist.proto.KlogistProtos.Person>(person_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          kdevelop.klogist.proto.KlogistProtos.Person, kdevelop.klogist.proto.KlogistProtos.Person.Builder, kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public java.util.List<kdevelop.klogist.proto.KlogistProtos.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public kdevelop.klogist.proto.KlogistProtos.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder setPerson(
          int index, kdevelop.klogist.proto.KlogistProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder setPerson(
          int index, kdevelop.klogist.proto.KlogistProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder addPerson(kdevelop.klogist.proto.KlogistProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder addPerson(
          int index, kdevelop.klogist.proto.KlogistProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder addPerson(
          kdevelop.klogist.proto.KlogistProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder addPerson(
          int index, kdevelop.klogist.proto.KlogistProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends kdevelop.klogist.proto.KlogistProtos.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public kdevelop.klogist.proto.KlogistProtos.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public java.util.List<? extends kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public kdevelop.klogist.proto.KlogistProtos.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public kdevelop.klogist.proto.KlogistProtos.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, kdevelop.klogist.proto.KlogistProtos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .klogist.Person person = 2;</code>
       */
      public java.util.List<kdevelop.klogist.proto.KlogistProtos.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          kdevelop.klogist.proto.KlogistProtos.Person, kdevelop.klogist.proto.KlogistProtos.Person.Builder, kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              kdevelop.klogist.proto.KlogistProtos.Person, kdevelop.klogist.proto.KlogistProtos.Person.Builder, kdevelop.klogist.proto.KlogistProtos.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:klogist.RespPerson)
    }

    static {
      defaultInstance = new RespPerson(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:klogist.RespPerson)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_klogist_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_klogist_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_klogist_ReqAddPerson_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_klogist_ReqAddPerson_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_klogist_RespPerson_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_klogist_RespPerson_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rklogist.proto\022\007klogist\"\"\n\006Person\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"/\n\014ReqAddPerson\022\037\n\006" +
      "person\030\001 \001(\0132\017.klogist.Person\"@\n\nRespPer" +
      "son\022\021\n\006Result\030\001 \002(\005:\0010\022\037\n\006person\030\002 \003(\0132\017" +
      ".klogist.PersonB\'\n\026kdevelop.klogist.prot" +
      "oB\rKlogistProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_klogist_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_klogist_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_klogist_Person_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_klogist_ReqAddPerson_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_klogist_ReqAddPerson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_klogist_ReqAddPerson_descriptor,
        new java.lang.String[] { "Person", });
    internal_static_klogist_RespPerson_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_klogist_RespPerson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_klogist_RespPerson_descriptor,
        new java.lang.String[] { "Result", "Person", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
